{% set name = "cdsdashboards" %}
{% set version = "0.3.3" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d518dbcc6466d07f95a945852eb5a912ba8e1c5078009d3cc184d1105c91511

build:
  noarch: python
  number: {{ build_number }}

outputs:
  - name: {{ name|lower }}
    build:
      number: {{ build_number }}
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - python >=3.6.0,<4.0.0
        - pip
      run:
        - python >=3.6.0,<4.0.0
        - tornado >=6.0.4
        - traitlets
        - jupyterhub >=1.0.0
        - alembic
        - pluggy
    test:
      imports:
        - cdsdashboards
      requires:
        - pip
      commands:
        - pip check
  - name: {{ name|lower }}-singleuser
    build:
      number: {{ build_number }}
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
        - jhsingle-native-proxy >=0.5.2
        - bokeh-root-cmd >=0.0.5
        - plotlydash-tornado-cmd >=0.0.4
    test:
      requires:
        - bokeh
      imports:
        - cdsdashboards
        - jhsingle_native_proxy
        - bokeh_root_cmd
        - plotlydash_tornado_cmd
      commands:
        - jhsingle-native-proxy --help
        - bokeh-root-cmd --help
        - plotlydash-tornado-cmd --help

about:
  home: https://github.com/ideonate/cdsdashboards
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Dashboard publishing solution for Data Science teams to share results with decision makers.
  doc_url: https://cdsdashboards.readthedocs.io/
  dev_url: https://github.com/ideonate/cdsdashboards

extra:
  feedstock-name: {{ name|lower }}
  recipe-maintainers:
    - danlester
    - fcollonval
